# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4d808c8cd7f557e417aef1a072591726"
name = "novanest"
handle = "novanest"
application_url = "https://reaching-below-nav-biological.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "novaanestt.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://reaching-below-nav-biological.trycloudflare.com/auth/callback",
  "https://reaching-below-nav-biological.trycloudflare.com/auth/shopify/callback",
  "https://reaching-below-nav-biological.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
